version: '3.8'

services:
  postgres:
    container_name: fast-feet-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fast-feet
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
